config/routes.rb
Rails.application.routes.draw do

  resources :roles
  resources :users
  resources :categories
  resources :items
  resources :material_items
  resources :materials
  devise_for :users, path: 'auth'

end

app/models/material_item.rb
class MaterialItem < ActiveRecord::Base
  belongs_to :material
end

app/controllers/material_items_controller.rb
class MaterialItemsController < ApplicationController
  before_action :set_material_item, only: [:show, :edit, :update, :destroy]

  # GET /material_items
  # GET /material_items.json
  def index
    @material_items = MaterialItem.all
  end

  # GET /material_items/1
  # GET /material_items/1.json
  def show
  end

  # GET /material_items/new
  def new
    @material_item = MaterialItem.new
  end

  # GET /material_items/1/edit
  def edit
  end

  # POST /material_items
  # POST /material_items.json
  def create
    @material_item = MaterialItem.new(material_item_params)

    respond_to do |format|
      if @material_item.save
        format.html { redirect_to @material_item, notice: 'Material item was successfully created.' }
        format.json { render :show, status: :created, location: @material_item }
      else
        format.html { render :new }
        format.json { render json: @material_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /material_items/1
  # PATCH/PUT /material_items/1.json
  def update
    respond_to do |format|
      if @material_item.update(material_item_params)
        format.html { redirect_to @material_item, notice: 'Material item was successfully updated.' }
        format.json { render :show, status: :ok, location: @material_item }
      else
        format.html { render :edit }
        format.json { render json: @material_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_items/1
  # DELETE /material_items/1.json
  def destroy
    @material_item.destroy
    respond_to do |format|
      format.html { redirect_to material_items_url, notice: 'Material item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_item
      @material_item = MaterialItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_item_params
      params.require(:material_item).permit(:company_name, :cnpj, :value, :website)
    end
end

app/views/material_items/_form.html.erb
<%= simple_form_for(@material_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company_name %>
    <%= f.input :cnpj %>
    <%= f.input :value %>
    <%= f.input :website %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/material_items/edit.html.erb
<h1>Editing Material Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @material_item %> |
<%= link_to 'Back', material_items_path %>

app/views/material_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Material Items</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Cnpj</th>
      <th>Value</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material_items.each do |material_item| %>
      <tr>
        <td><%= material_item.company_name %></td>
        <td><%= material_item.cnpj %></td>
        <td><%= material_item.value %></td>
        <td><%= material_item.website %></td>
        <td><%= link_to 'Show', material_item %></td>
        <td><%= link_to 'Edit', edit_material_item_path(material_item) %></td>
        <td><%= link_to 'Destroy', material_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material item', new_material_item_path %>

app/views/material_items/new.html.erb
<h1>New Material Item</h1>

<%= render 'form' %>

<%= link_to 'Back', material_items_path %>

app/views/material_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @material_item.company_name %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @material_item.cnpj %>
</p>

<p>
  <strong>Value:</strong>
  <%= @material_item.value %>
</p>

<p>
  <strong>Website:</strong>
  <%= @material_item.website %>
</p>

<%= link_to 'Edit', edit_material_item_path(@material_item) %> |
<%= link_to 'Back', material_items_path %>