config/routes.rb
Rails.application.routes.draw do

  resources :roles
  resources :users
  resources :categories
  resources :items
  resources :material_items
  resources :materials
  devise_for :users, path: 'auth'

end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :user
  has_many :items
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)
    @material.user = current_user
    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:user_id, :description, :specification, :status, :type_material, :amount, :finality, :note ,items_attributes: [:id, :company_name, :cnpj, :value, :website, :_destroy, :attach])
    end
end

app/views/materials/_form.html.erb
<%= simple_form_for @material, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :description , placeholder: "Descrição do material" %>
  <%= error_span(@material[:description]) %>
  <%= f.input :specification , as: :text , placeholder: "Especificação do material" %>
  <%= error_span(@material[:specification]) %>
  <%= f.input :type_material , collection: [["Permanente","0"],["Consumo","1"]]%>
  <%= error_span(@material[:type_material]) %>
  <%= f.input :amount %>
  <%= error_span(@material[:amount]) %>
  <%= f.input :finality, as: :text , placeholder: "Finalidade para o material" %>
  <%= error_span(@material[:finality]) %>
  <%= f.input :note , as: :text , placeholder: "Observações" %>
  <%= error_span(@material[:note]) %>

  <%= f.simple_fields_for :items do |item| %>
    <%= render 'item_fields', f: item %>
  <%end %>
    <div id="links" class="links">
      <%= link_to_add_association 'Adicionar Cotação', f, :items ,:class => 'btn btn-primary' %>
    </div>
<br/>
    <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                materials_path, :class => 'btn btn-default' %>
<% end %>

app/views/materials/_item_fields.html.erb
<div class="nested-fields">
  <fieldset>
    <legend>Cotação</legend>
  <%= f.input :company_name %>
  <%= f.input :cnpj %>
  <%= f.input :value %>
  <%= f.input :website %>
    <%= f.input :attach , as: :file %>
  <%= link_to_remove_association "Apagar Cotação", f , class: 'btn btn-danger' %>
  </fieldset>
  <br/>
</div>

app/views/materials/edit.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/materials/index.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:specification) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:type_material) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:finality) %></th>
      <th><%= model_class.human_attribute_name(:note) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= link_to material.id, material_path(material) %></td>
        <td><%= material.user.username %></td>
        <td><%= material.description %></td>
        <td><%= material.specification %></td>
        <td><%= material.status %></td>
        <td><%= material.type_material %></td>
        <td><%= material.amount %></td>
        <td><%= material.finality %></td>
        <td><%= material.note %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_material_path(material), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      material_path(material),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_material_path,
            :class => 'btn btn-primary' %>

app/views/materials/new.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/materials/show.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @material.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @material.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:specification) %>:</strong></dt>
  <dd><%= @material.specification %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @material.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_material) %>:</strong></dt>
  <dd><%= @material.type_material %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @material.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:finality) %>:</strong></dt>
  <dd><%= @material.finality %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @material.note %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              materials_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_material_path(@material), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              material_path(@material),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>